spring:
  application:
    name: task-resolver
  profiles:
    active:
db:
  host: ec2-54-75-246-118.eu-west-1.compute.amazonaws.com
  port: 5432
  database: d9l8av2g72eh0o
  username: mzmftvajoxvdzl
  password: 7bb000c24a14d37c1d99b25b3eb5fee3bc703149af9161b2923e4c3029210c40
rest:
  base-url:
    task-provider: http://greenapp-task-provider.herokuapp.com
    reward-manager: http://greenapp-reward-manager.herokuapp.com
kafka:
  properties:
    "[bootstrap.servers]": moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    "[sasl.jaas.config]": org.apache.kafka.common.security.scram.ScramLoginModule required username="2z2j7jw9" password="gGBcXuQW6peGnHhInj9TE09n_d4IadbE";
    "[group.id]": 2z2j7jw9-consumer
    "[security.protocol]": SASL_SSL
    "[sasl.mechanism]": SCRAM-SHA-256
  topic: 2z2j7jw9-task-event
task:
  processing:
    waiting-for-approve-m: 1
    resolved-m: 1
    waiting-for-approve-count: 1
    resolved-count: 1
client:
  reward:
    approve-attendee: 100
    complete-attendee: 100
    trash-attendee: 20
    creator: 200